import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import TanStackQuery from '@/components/TanStackQuery/TanStackQuery';

export const metadata: Metadata = {
  title: '06 notehub nextjs',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TanStackQuery>
          <Header />
          {children}
          <Footer />
        </TanStackQuery>
      </body>
    </html>
  );
}
